### ISSUE TITLE
Refactor inference to use a python script instead of bash

### ISSUE THREAD

**Issue by kartikey-vyas** [ersilia-os/model-inference-pipeline#22]
Currently, `predict.yml` uses several shell commands to:
- split the input CSV into a slice for the worker to look at
- call the ersilia model hub
- fetch and run the specified model
- upload predictions to S3

All of this can be done in python efficiently, in a manner which will allow us to better maintain and test the code. We want to write this python script and replace the bash with a call to this script..

**Comment by kabilank6** [comment]
Now having a look!

**Comment by kabilank6** [comment]
Do I have write access to this repo @kartikey-vyas ?

**Comment by kartikey-vyas** [comment]
have added you
